//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trello.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trello.Helpers.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.trello.com.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards?name={0}&amp;desc={1}&amp;closed={2}&amp;key=ccb12ad790633da2de89ccc4e70cd59e&amp;token=dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb.
        /// </summary>
        internal static string CreateBoard {
            get {
                return ResourceManager.GetString("CreateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}/lists?key=ccb12ad790633da2de89ccc4e70cd59e&amp;token=dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb&amp;name={1}.
        /// </summary>
        internal static string CreateList {
            get {
                return ResourceManager.GetString("CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}?key=ccb12ad790633da2de89ccc4e70cd59e&amp;token=dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb.
        /// </summary>
        internal static string DeleteBoard {
            get {
                return ResourceManager.GetString("DeleteBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/members/lauradunca2/boards?key=ccb12ad790633da2de89ccc4e70cd59e&amp;token=dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb.
        /// </summary>
        internal static string GetBoards {
            get {
                return ResourceManager.GetString("GetBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}?key=ccb12ad790633da2de89ccc4e70cd59e&amp;token=dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb&amp;name={1}.
        /// </summary>
        internal static string UpdateBoard {
            get {
                return ResourceManager.GetString("UpdateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lauradunca2.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
