//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trello.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trello.Helpers.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.trello.com.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards?name={0}&amp;desc={1}&amp;closed={2}&amp;key={3}&amp;token={4}.
        /// </summary>
        internal static string CreateBoard {
            get {
                return ResourceManager.GetString("CreateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/cards?key={0}&amp;token={1}&amp;idList={2}&amp;name={3}&amp;desc={4}.
        /// </summary>
        internal static string CreateCard {
            get {
                return ResourceManager.GetString("CreateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}/lists?key={1}&amp;token={2}&amp;name={3}.
        /// </summary>
        internal static string CreateList {
            get {
                return ResourceManager.GetString("CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}?key={1}&amp;token={2}.
        /// </summary>
        internal static string DeleteBoard {
            get {
                return ResourceManager.GetString("DeleteBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laura_dunca@outlook.com.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/members/{0}/boards?key={1}&amp;token={2}.
        /// </summary>
        internal static string GetBoards {
            get {
                return ResourceManager.GetString("GetBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/cards/{0}?key={1}&amp;token={2}.
        /// </summary>
        internal static string GetCard {
            get {
                return ResourceManager.GetString("GetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/lists/{0}?key={1}&amp;token={2}.
        /// </summary>
        internal static string GetList {
            get {
                return ResourceManager.GetString("GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}/lists?key={1}&amp;token={2}.
        /// </summary>
        internal static string GetLists {
            get {
                return ResourceManager.GetString("GetLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccb12ad790633da2de89ccc4e70cd59e.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://trello.com/login.
        /// </summary>
        internal static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enFRYsHLGSkGmQ7.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dcd06124ded1c0d963e61ba71442f8965243bb98e9afdc72eca4833e3b403fbb.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/boards/{0}?key={1}&amp;token={2}&amp;name={3}.
        /// </summary>
        internal static string UpdateBoard {
            get {
                return ResourceManager.GetString("UpdateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/cards/{0}?key={1}&amp;token={2}&amp;idList={3}.
        /// </summary>
        internal static string UpdateCardList {
            get {
                return ResourceManager.GetString("UpdateCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/cards/{0}?key={1}&amp;token={2}&amp;name={3}.
        /// </summary>
        internal static string UpdateCardName {
            get {
                return ResourceManager.GetString("UpdateCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1/cards/{0}?key={1}&amp;token={2}&amp;closed={3}.
        /// </summary>
        internal static string UpdateCardStatus {
            get {
                return ResourceManager.GetString("UpdateCardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lauradunca2.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
